### ISSUE TITLE
Add install libxcb-cursor-dev to ci.yml

### ISSUE THREAD

**Issue by thompson318** [SciKit-Surgery/scikit-surgeryutils#56]
Whilst testing https://github.com/SciKit-Surgery/snappysonic/issues/26 I found that adding libxcb-cursor-dev to the installation fixed the seg faults on ubuntu. We should test if it does the same here and in surgeryvtk

**Comment by mxochicale** [comment]
It has been fixed here https://github.com/SciKit-Surgery/scikit-surgeryutils/commit/5289cff262e63686f8d1c1260e83bec7bc9cdce9 and will be part of release v2.0.0

**Comment by mxochicale** [comment]
Sorted out here https://github.com/SciKit-Surgery/scikit-surgeryutils/pull/59/commits/6c5df68e4fb7033e07aac8bb79a67c9cea79c2f8
